README.md

Fixes #15
Not sure if this is the way to go, since this issue is still open: https://github.com/apollographql/graphql-tools/issues/957
But it fixed it for me.

Explicitely define constraint in schema

---

package-lock.json
package.json

also updated graphql version range in peer dependencies to suppress warnings
When using this package with graphql 15 I get an `Must provide Source.
Received: undefined.` error which should be fixed in https://github.com/Urigo/graphql-tools/pull/1353

fix: update gql-tools for graphql 15 compatibility

---

.travis.yml

noticed this when looking into the graphql-tools issue, so why not fix it :man_shrugging: 
updates matrix to test current node lts releases/removes unsupported versions

fix: update travis matrix to node lts releases

---

index.js
scalars/number.js
test/float.test.js

[issue#78](https://github.com/confuser/graphql-constraint-directive/issues/78)
Number constraints
The types of min, max, exclusiveMin, exclusiveMax, and multipleOf were modified from Int to Float.
The name of the generated scalar was created by modifying the decimal point to dot to distinguish between the integer case and the real case. eg. id_Float_NotNull_min_2dot99

Fix issue #78

---

index.js
test/argument.test.js

Here is PR which should fix #11 by adding `ARGUMENT_DEFINITION` in directive and in mapSchema function.
Covered by couple of tests on int input variable.

Allow directive to work on argument definition

---

lib/query-validation-visitor.js
test/array-size.test.js

This PR fixes array/list size validation to work for list of other scalar types (ID, Boolean)

fix: array/list size validation for list of other scalar types

---

index.d.ts

fixes https://github.com/confuser/graphql-constraint-directive/issues/107
`createApolloQueryValidationPlugin` typing definition to match the implementation

fix: createApolloQueryValidationPlugin typing

---

README.md

- Closes #132 
Adding a basic quickstart demo, based on small tweaks needed to work with `apollo-subgraph`. As per #132

docs(apollo-subgraph): adding quickstart instructions for a subgraph

---

lib/query-validation-visitor.js
test/string.test.js

I noticed that empty strings (`""`) are not validated.
In this PR I wrote a test for this case and solved the bug.

fix: validate empty strings

---

lib/query-validation-visitor.js
test/argument-dynamic.test.js
test/argument.test.js
test/array-size.test.js
test/array-structures.test.js
test/array.test.js
test/float.test.js
test/fragment-inline.test.js
test/fragment.test.js
test/input-object.test.js
test/int.test.js
test/introspection.test.js
test/setup-apollo-plugin.js
test/setup-envelop-plugin.js
test/setup-schema-wrapper.js
test/setup-validation-rule-express-graphql.js
test/string.test.js
test/testsuite-apollo-plugin.js
test/testsuite-envelop-plugin.js
test/testsuite-schema-wrapper.js
test/testsuite-validation-rule-express-graphql.js
test/variable.test.js

I was able to reproduce bug #145 and patch it.
Also sanitized other two places with potential for similar problem, even no test exists to break them.
Test setup method signature had to be changed to allow optional parameters.

#145 - server plugins based validation fails when dynamic argument used

---

README.md
apollo4.d.ts
apollo4.js
test/setup-apollo4-plugin.js

It is not necessary anymore to provide schema during the Apollo 4 plugin creation, it is obtained from the server automatically.
Change is backward compatible, I marked `schema` option in the `.d.ts` file as an optional and documented it as deprecated.
Documentation updated and improved (Apollo 4 plugin example simplified, added info about required dependencies for distinct plugins to solve #151 ).

Apollo 4 plugin schema loading improvement

---

README.md
index.d.ts
index.js
package.json
test/snapshots/ws-1.txt
test/snapshots/ws-2-2.txt
test/snapshots/ws-2.txt
test/snapshots/ws-3.txt
test/testsuite-documentation.js
test/testsuite-full.js

As requested in #4 created schema transformer which adds documentation to fields and arguments where `@constraint` directive is used.
[CommonMark](https://spec.commonmark.org) markdown is used in default documentation texts as it is allowed by the GraphQL specification
Constraint description consist of header and list with items for each validated condition. 
If field/argument description exists already, the constraint description is appended to it as new paragraph.
Documentation of the constraints is not added if it already exists (checked over presence of the header)
Both header and condition descriptions can be customized during the transformer creation.
Everything is tested.

Schema documentation transformation - #4

---

index.d.ts

Seems like explicitly defining the class signatures fixes compilation errors with `tsc`
Let me know if you don't agree with this approach!

Fix #172 declaration of QueryValidationVisitor

---

README.md
apollo4.js
index.js
lib/query-validation-visitor.js
scalars/string.js
test/setup-apollo-plugin.js
test/setup-apollo4-plugin.js
test/setup-envelop-plugin.js
test/setup-schema-wrapper.js
test/setup-validation-rule-express-graphql.js
test/string.test.js

I've added a feature that allows the use of custom formats. The README.md has also been updated which shows how it works and how to use it through the JS API.

Add support for passing custom formats

---

lib/query-validation-visitor.js
test/variable.test.js

#133 and #177 fixed this for input objects, but not query values.
Sending a 0 value on an int with min constraint or an empty string on a string with minLength constraint would skip validation previously.
Making the values non-nullable doesn't help, and using defaults (in a resolver) _can_ help, but not for all cases. For instance for an auth query you don't want to give a username a default and cause db queries for something that should be failing validation.
See #187 for an example of the problem.

Fix falsy string and int query values

---

index.d.ts

This adds some missing types for the plugin options, mainly the `formats` documented in https://github.com/confuser/graphql-constraint-directive#custom-format

fix: Add plugin options types

---

index.js

In our project, we use `printSchemaWithDirectives` method from some library, which prefers `description` from `astNode`. So this change only makes sure that both descriptions are the same.

patched documentation schema transformer to change description in astNode also

---

apollo4.d.ts
index.d.ts
package.json

Custom format validation was not working for apollo server 4 plugin due incorrect options parameter. Fixed the parameter to match javascript files.

fix: Updated apollo server 4 typescript d files to match javascript

---

lib/type-utils.js
test/id.test.js

this will allow custom format on the ID scalar.
`export declare const GraphQLString: GraphQLScalarType<string, string>;
export declare const GraphQLID: GraphQLScalarType<string, string>;`

adding support for the id scalar constrained as a string

---

index.js
test/string.test.js

Yoga only will show the code, field, context if they are part of the extensions object.
Before:
After:

fix: yoga server not showing envelop extensions

---

lib/query-validation-visitor.js
test/foreign-query-directives.test.js
test/testsuite-apollo-plugin.js

We ran into an issue when using a unrelated query directive together with graphql-constraint-directive, where the createApolloQueryValidationPlugin would throw an error whenever the client had a query using that directive. 
The error was:
```
{
"errors": [
{
"message": "Cannot read properties of undefined (reading 'args')",
"extensions": {
"code": "INTERNAL_SERVER_ERROR"
}
}
]
}
```
And our directive was:
`directive @component(name: String!) on QUERY | MUTATION | SUBSCRIPTION`
It appears that this fixes it, and I also added tests.

Fix for trying to read args on undefined

---

.github/workflows/build.yaml
apollo4.js
index.js
lib/error.js
lib/type-utils.js
lib/validate-query.js
package-lock.json
package.json
test/typescript/apollo.ts
test/typescript/apollo4.ts
test/typescript/error.ts
tsconfig.apollo.json
tsconfig.apollo4.json

I've fixed the underlying issue (as well as a few other type discovered while type-checking the apollo4 code). There are a few bugfix commits that can be cherry-picked out if necessary:
- db69dbea5d06b3eed7073fa14b5e53b48a4863e7
- 89b1c56aeb99c03f209839bb91c88d683eb4b7a0
Ultimately this PR:
1. Attempts to import the code of the `graphql-constraint-directive` package in a typescript library as a consumer would.
2. Provides a new npm script to attempt to compile the code.
3. Fixes type errors discovered during compilation.
4. Moves the validateQuery into separate module so that it can be referenced by the Apollo3 and Apollo4 code without accidentally bringing in unexpected dependencies.
Importantly, for Apollo4, the `apollo-server-errors` package is no longer necessary and I added [an …

Fix `apollo-server-errors` import for typescript projects using apollo4
